# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fabe7c6711bfe7e82c390a89c0ee0faf65a571ed4d3e9b48e337618adedaafae4f5cd2eb52226372b82eb6854f0039969ccef9b717b4ee092ecd8bf47928e82f

test:
  secret_key_base: fa9b7387250afebe2a880b662c6a6db51b9c69a32319e3e8f524ee1cccf41f39b68a3d5e99b42319fdae916bf429ae03871f4802d99ab320e45fe65521dbdb4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
